#!/bin/bash
# tokdec - Decrypt tokens.secrets
# Depends on openssl-tool package

# Check the dependency
if ! command -v openssl > /dev/null; then
    echo "openssl not found" 1>&2
    exit 1
fi

# Initial settings
rc=${TOKENSRC:-~/.tokensrc}
[[ -r "$rc" ]] && source "$rc"
secretsfile=${secretsfile:-tokens.secrets}
cipherfile="${secretsfile}.cipher"

# Pick the passphrase
read -sp "Enter the passphrase: " tokpass; echo 1>&2
export tokpass

# Decrypt the secrets file
openssl enc -aes128 -d -in "$cipherfile" -pass env:tokpass -pbkdf2 | gzip -d > "$secretsfile"
[[ 0 -ne $? ]] && echo "Check the passphrase" 1>&2
