#!/bin/bash
# tokdec - Decrypt tokens.secrets
# Depends on openssl-tool package

# Check the dependency
if ! command -v openssl > /dev/null; then
    echo "openssl not found" 1>&2
    exit 1
fi

# Check if the version of OpenSSL is 1.1.1 or greater and add -pbkdf2 parameter
ossl111=""
read -r vmajor vminor vpatch <<< "$(
    openssl version | while read -ra v; do v1="${v[1]}"; echo "${v1//./ }"; done
)"
read -r vmajor vminor vpatch <<< "${vmajor//[^0-9]/} ${vminor//[^0-9]/} ${vpatch//[^0-9]/}"
if [[
        1 -lt $vmajor
        || (1 -eq $vmajor && 1 -lt $vminor)
        || (1 -eq $vmajor && 1 -eq $vminor && 1 -le $vpatch)
    ]]; then
    ossl111="-pbkdf2" 
fi

# Initial settings
rc=${TOKENSRC:-~/.tokensrc}
# shellcheck source=.tokensrc
[[ -r "$rc" ]] && source "$rc"
secretsfile=${secretsfile:-tokens.secrets}
cipherfile="${secretsfile}.cipher"

# Pick the passphrase
read -rsp "Enter the passphrase: " tokpass; echo 1>&2
export tokpass

# Decrypt the secrets file
if ! openssl enc -aes128 -d -in "$cipherfile" -pass env:tokpass $ossl111 | gzip -d > "$secretsfile"; then
    echo "Check the passpharse" 1>&2
fi
