#!/bin/sh
# tokens - shows time-based one-time passwords - TOTP
# Depends on oathtool package

#secretsfile=~/bin/tokens.secrets
secretsfile=tokens.secrets

while true; do
    clear
    seconds=`date '+%S'`
    remaining=`expr 30 - $seconds % 30`
    now=`date --iso-8601=seconds`
    printf '%s\nRemaining : %6d\n\n' $now $remaining
    while read name secret; do
        token=`oathtool --totp --base32 $secret`
        printf '%-10s: %s\n' $name $token
    done < $secretsfile
    echo; echo -n "Type Ctrl-C to exit"
    sleep 1
done
