#!/bin/bash
# tokens - shows time-based one-time passwords - TOTP
# Depends on oathtool package

rc=~/.tokensrc
[ -r $rc ] && . $rc
[ -z "$secretsfile" ] && secretsfile=tokens.secrets
[ -z "$barsytle" ] && barstyle=':.'
XCLIP=""
[ -z "$XCLIP" ] && which xclip > /dev/null && XCLIP="xclip"
[ -z "$XCLIP" ] && which xsel > /dev/null && XCLIP="xsel"

lasthalf=-1
while true; do
    seconds=$(date '+%-S')
    half=$(($seconds / 30))
    remaining=$((30 - $seconds % 30))
    if [ $half -ne $lasthalf ]; then
        lasthalf=$half
        declare -a keys=({1..9} {a..z} {A..Z})
        declare -A tokens
        cnt=0
        while read name secret; do
            token=$(oathtool --totp --base32 $secret)
            tokens[${keys[$cnt]}]="$name $token"
            cnt=$((1 + $cnt))
        done < $secretsfile
        clear
        cnt=0
        while [ $cnt -lt ${#tokens[@]} ]; do
            printf '%s) %-10.10s: %s\n' ${keys[$cnt]} ${tokens[${keys[$cnt]}]}
            cnt=$((1 + $cnt))
        done
        echo '0) Exit'
    fi
    bar=$(printf '%-030.*d' $remaining 0 | tr '0 ' "$barstyle")
    now=$(date '+%Y-%m-%d %H:%M:%S')
    printf '\r   Remaining : %6d %s  %s ' $remaining "$bar" "$now"
    read -N 1 -t 1 -s key
    case "$key" in
        "")
            ;;
        0)
            echo
            break
            ;;
        [1-9a-zA-Z])
            [ -n "$XCLIP" ] && [ -n "${tokens[$key]}" ] \
                && echo ${tokens[$key]} | cut -d' ' -f2 | $XCLIP -i
            ;;
    esac
done
