#!/bin/bash
# tokenc - Encrypt tokens.secrets
# Depends on openssl-tool package

# Check the dependency
if ! command -v openssl > /dev/null; then
    echo "openssl not found" 1>&2
    exit 1
fi

# Check if the version of OpenSSL is 1.1.1 or greater and add -pbkdf2 parameter
ossl111=""
read vmajor vminor vpatch <<< $(openssl version | while read o v rr; do echo ${v//./ }; done)
if [[
        1 -lt $vmajor
        || (1 -eq $vmajor && 1 -lt $vminor)
        || (1 -eq $vmajor && 1 -eq $vminor && 1 -le $vpatch)
    ]]; then
    ossl111="-pbkdf2" 
fi

# Initial settings
rc=${TOKENSRC:-~/.tokensrc}
[[ -r "$rc" ]] && source "$rc"
secretsfile=${secretsfile:-tokens.secrets}
cipherfile="${secretsfile}.cipher"

# Pick the passphrase
((tokpass = "0"))
((verpass = "1"))
while true; do
    read -sp "Enter the passphrase: " tokpass; echo 1>&2
    if [[ ${#tokpass} -lt 4 ]]; then
        echo "Length of the passphrase must be at least four characters" 1>&2
        continue
    fi
    read -sp "Repeat the passphrase: " verpass; echo 1>&2
    if [[ $tokpass != $verpass ]]; then
        echo "The passphrase differs from its verification" 1>&2
        continue
    fi
    break
done
export tokpass

# Encrypt the secrets file
openssl enc -aes128 -e -in <(gzip -c "$secretsfile") -out "$cipherfile" -pass env:tokpass $ossl111
[[ 0 -eq $? ]] && rm -f "$secretsfile"
