#!/bin/bash
# tokenc - Encrypt tokens.secrets
# Depends on openssl-tool package

# Check the dependency
if ! command -v openssl > /dev/null; then
    echo "openssl not found" 1>&2
    exit 1
fi

# Initial settings
rc=${TOKENSRC:-~/.tokensrc}
[[ -r "$rc" ]] && source "$rc"
secretsfile=${secretsfile:-tokens.secrets}
cipherfile="${secretsfile}.cipher"

# Pick the passphrase
((tokpass = "0"))
((verpass = "1"))
while true; do
    read -sp "Enter the passphrase: " tokpass; echo 1>&2
    if [[ ${#tokpass} -lt 4 ]]; then
        echo "Length of the passphrase must be at least four characters" 1>&2
        continue
    fi
    read -sp "Repeat the passphrase: " verpass; echo 1>&2
    if [[ $tokpass != $verpass ]]; then
        echo "The passphrase differs from its verification" 1>&2
        continue
    fi
    break
done
export tokpass

# Encrypt the secrets file
openssl enc -aes128 -e -in <(gzip -c "$secretsfile") -out "$cipherfile" -pass env:tokpass -pbkdf2
[[ 0 -eq $? ]] && rm -f "$secretsfile"
